### ISSUE TITLE
Comments and questions

### ISSUE THREAD

**Issue by pllim** [spacetelescope/action-publish_to_pypi#2]
1. Would be nice to have some examples of what makes a good version and a bad one.
2. What if a PyPI package of that name exists already but not ours?
3. "Whenever a new release with a semver-compliant tag is made on Github from the repository, ..." -- So, not only the tag needs to be semver, but the person need to push the "edit tag" and then "publish release" buttons, right? This should be made clearer.
4. "an e-mail message" -- Whose email will it use? Is it customizable, say, to point to a mailing list?
5. Nice to have: Screenshots to go with the instructions.

**Comment by pllim** [comment]
6. What if someone re-edit a GitHub release tag? What is the intended behavior?

**Comment by rendinam** [comment]
>     1. Would be nice to have some examples of what makes a good version and a bad one.
Added to docs.

>     2. What if a PyPI package of that name exists already but not ours?
The publication will fail when the upload credentials are not honored.

>     3. "Whenever a new release with a semver-compliant tag is made on Github from the repository, ..." -- So, not only the tag needs to be semver, but the person need to push the "edit tag" and then "publish release" buttons, right? This should be made clearer.
This assumes the developer has pushed a tag separately and is not relying upon the Github release generation from creating it, which is fine. Ultimately, the tag that is specified in the Github release input field must be semver-compliant, whether it exists already or not.

>     4. "an e-mail message" -- Whose email will it use? Is it customizable, say, to point to a mailing list?
The e-mail is sent to everyone who is subscribed to notifications from the repository in question. This behavior is determined by Github Actions. The docs have been clarified.

>     5. Nice to have: Screenshots to go with the instructions.
Perhaps soon.

>     6. What if someone re-edit a GitHub release tag? What is the intended behavior?
The workflow only triggers on new releases, so no automatic action will be taken.

**Comment by pllim** [comment]
Thanks! When you feel like all points are addressed, feel free to close.
